//
//  File.swift
//  DesignTokens
//
//  Created by Astemir Shibzuhov on 02.11.2024.
//

import UIKit

public struct SFIcon {
    private let name: String
    public let icon: UIImage
    
    init(name: String) {
        self.name = name
        self.icon = UIImage.fromSF(by: name)
    }
    
    public func withSize(size: CGFloat, weight: UIImage.SymbolWeight) -> UIImage {
        return UIImage.fromSF(by: name, size: size, weight: weight)
    }
}


public struct AppImages {
    public struct Icons {
        public let close = UIImage.fromResources(by: "close")
        public let columns = UIImage.fromResources(by: "columns")
        public let underline = UIImage.fromResources(by: "underline")
        public let grid = UIImage.fromResources(by: "grid")
        public let triangle = UIImage.fromResources(by: "triangle")
        public let search = UIImage.fromResources(by: "search")
        public let volume2 = UIImage.fromResources(by: "volume-2")
        public let arrowUpCircle = UIImage.fromResources(by: "arrow-up-circle")
        public let pauseCircle = UIImage.fromResources(by: "pause-circle")
        public let checkSquare = UIImage.fromResources(by: "check-square")
        public let arrowDown = UIImage.fromResources(by: "arrow-down")
        public let figma = UIImage.fromResources(by: "figma")
        public let cornerRightUp = UIImage.fromResources(by: "corner-right-up")
        public let chevronsRight = UIImage.fromResources(by: "chevrons-right")
        public let list = UIImage.fromResources(by: "list")
        public let chevronsDown = UIImage.fromResources(by: "chevrons-down")
        public let wind = UIImage.fromResources(by: "wind")
        public let cornerUpRight = UIImage.fromResources(by: "corner-up-right")
        public let target = UIImage.fromResources(by: "target")
        public let scissors = UIImage.fromResources(by: "scissors")
        public let minimize2 = UIImage.fromResources(by: "minimize-2")
        public let playCircle = UIImage.fromResources(by: "play-circle")
        public let crosshair = UIImage.fromResources(by: "crosshair")
        public let airplay = UIImage.fromResources(by: "airplay")
        public let xOctagon = UIImage.fromResources(by: "x-octagon")
        public let repeatIcon = UIImage.fromResources(by: "repeat")
        public let edit3 = UIImage.fromResources(by: "edit-3")
        public let volume1 = UIImage.fromResources(by: "volume-1")
        public let sunrise = UIImage.fromResources(by: "sunrise")
        public let toggleRight = UIImage.fromResources(by: "toggle-right")
        public let umbrella = UIImage.fromResources(by: "umbrella")
        public let user = UIImage.fromResources(by: "user")
        public let fileMinus = UIImage.fromResources(by: "file-minus")
        public let xCircle = UIImage.fromResources(by: "x-circle")
        public let circle = UIImage.fromResources(by: "circle")
        public let phoneMissed = UIImage.fromResources(by: "phone-missed")
        public let edit2 = UIImage.fromResources(by: "edit-2")
        public let cornerLeftUp = UIImage.fromResources(by: "corner-left-up")
        public let home = UIImage.fromResources(by: "home")
        public let gitlab = UIImage.fromResources(by: "gitlab")
        public let music = UIImage.fromResources(by: "music")
        public let smartphone = UIImage.fromResources(by: "smartphone")
        public let moreHorizontal = UIImage.fromResources(by: "more-horizontal")
        public let sliders = UIImage.fromResources(by: "sliders")
        public let arrowUpLeft = UIImage.fromResources(by: "arrow-up-left")
        public let chevronDown = UIImage.fromResources(by: "chevron-down")
        public let hexagon = UIImage.fromResources(by: "hexagon")
        public let github = UIImage.fromResources(by: "github")
        public let crop = UIImage.fromResources(by: "crop")
        public let tag = UIImage.fromResources(by: "tag")
        public let briefcase = UIImage.fromResources(by: "briefcase")
        public let rotateCw = UIImage.fromResources(by: "rotate-cw")
        public let map = UIImage.fromResources(by: "map")
        public let inbox = UIImage.fromResources(by: "inbox")
        public let alignJustify = UIImage.fromResources(by: "align-justify")
        public let plusSquare = UIImage.fromResources(by: "plus-square")
        public let power = UIImage.fromResources(by: "power")
        public let database = UIImage.fromResources(by: "database")
        public let cameraOff = UIImage.fromResources(by: "camera-off")
        public let toggleLeft = UIImage.fromResources(by: "toggle-left")
        public let file = UIImage.fromResources(by: "file")
        public let messageCircle = UIImage.fromResources(by: "message-circle")
        public let voicemail = UIImage.fromResources(by: "voicemail")
        public let terminal = UIImage.fromResources(by: "terminal")
        public let move = UIImage.fromResources(by: "move")
        public let maximize = UIImage.fromResources(by: "maximize")
        public let chevronUp = UIImage.fromResources(by: "chevron-up")
        public let arrowDownLeft = UIImage.fromResources(by: "arrow-down-left")
        public let fileText = UIImage.fromResources(by: "file-text")
        public let droplet = UIImage.fromResources(by: "droplet")
        public let zapOff = UIImage.fromResources(by: "zap-off")
        public let x = UIImage.fromResources(by: "x")
        public let barChart = UIImage.fromResources(by: "bar-chart")
        public let lock = UIImage.fromResources(by: "lock")
        public let logIn = UIImage.fromResources(by: "log-in")
        public let shoppingBag = UIImage.fromResources(by: "shopping-bag")
        public let divide = UIImage.fromResources(by: "divide")
        public let cloudDrizzle = UIImage.fromResources(by: "cloud-drizzle")
        public let refreshCw = UIImage.fromResources(by: "refresh-cw")
        public let chevronRight = UIImage.fromResources(by: "chevron-right")
        public let clipboard = UIImage.fromResources(by: "clipboard")
        public let package = UIImage.fromResources(by: "package")
        public let instagram = UIImage.fromResources(by: "instagram")
        public let link = UIImage.fromResources(by: "link")
        public let videoOff = UIImage.fromResources(by: "video-off")
        public let key = UIImage.fromResources(by: "key")
        public let meh = UIImage.fromResources(by: "meh")
        public let cornerDownRight = UIImage.fromResources(by: "corner-down-right")
        public let arrowRight = UIImage.fromResources(by: "arrow-right")
        public let aperture = UIImage.fromResources(by: "aperture")
        public let stopCircle = UIImage.fromResources(by: "stop-circle")
        public let logOut = UIImage.fromResources(by: "log-out")
        public let arrowLeftCircle = UIImage.fromResources(by: "arrow-left-circle")
        public let barChart2 = UIImage.fromResources(by: "bar-chart-2")
        public let gitPullRequest = UIImage.fromResources(by: "git-pull-request")
        public let minimize = UIImage.fromResources(by: "minimize")
        public let minusSquare = UIImage.fromResources(by: "minus-square")
        public let settings = UIImage.fromResources(by: "settings")
        public let cloudSnow = UIImage.fromResources(by: "cloud-snow")
        public let thumbsDown = UIImage.fromResources(by: "thumbs-down")
        public let type = UIImage.fromResources(by: "type")
        public let archive = UIImage.fromResources(by: "archive")
        public let phoneOutgoing = UIImage.fromResources(by: "phone-outgoing")
        public let pocket = UIImage.fromResources(by: "pocket")
        public let mail = UIImage.fromResources(by: "mail")
        public let shield = UIImage.fromResources(by: "shield")
        public let download = UIImage.fromResources(by: "download")
        public let phoneForwarded = UIImage.fromResources(by: "phone-forwarded")
        public let cornerRightDown = UIImage.fromResources(by: "corner-right-down")
        public let bookOpen = UIImage.fromResources(by: "book-open")
        public let divideSquare = UIImage.fromResources(by: "divide-square")
        public let server = UIImage.fromResources(by: "server")
        public let tv = UIImage.fromResources(by: "tv")
        public let skipForward = UIImage.fromResources(by: "skip-forward")
        public let volume = UIImage.fromResources(by: "volume")
        public let userPlus = UIImage.fromResources(by: "user-plus")
        public let batteryCharging = UIImage.fromResources(by: "battery-charging")
        public let layers = UIImage.fromResources(by: "layers")
        public let slash = UIImage.fromResources(by: "slash")
        public let radio = UIImage.fromResources(by: "radio")
        public let book = UIImage.fromResources(by: "book")
        public let userMinus = UIImage.fromResources(by: "user-minus")
        public let bell = UIImage.fromResources(by: "bell")
        public let gitBranch = UIImage.fromResources(by: "git-branch")
        public let coffee = UIImage.fromResources(by: "coffee")
        public let code = UIImage.fromResources(by: "code")
        public let thermometer = UIImage.fromResources(by: "thermometer")
        public let cast = UIImage.fromResources(by: "cast")
        public let flag = UIImage.fromResources(by: "flag")
        public let eyeOff = UIImage.fromResources(by: "eye-off")
        public let battery = UIImage.fromResources(by: "battery")
        public let disc = UIImage.fromResources(by: "disc")
        public let frown = UIImage.fromResources(by: "frown")
        public let tool = UIImage.fromResources(by: "tool")
        public let cpu = UIImage.fromResources(by: "cpu")
        public let bold = UIImage.fromResources(by: "bold")
        public let hash = UIImage.fromResources(by: "hash")
        public let share2 = UIImage.fromResources(by: "share-2")
        public let plus = UIImage.fromResources(by: "plus")
        public let check = UIImage.fromResources(by: "check")
        public let rotateCcw = UIImage.fromResources(by: "rotate-ccw")
        public let hardDrive = UIImage.fromResources(by: "hard-drive")
        public let bluetooth = UIImage.fromResources(by: "bluetooth")
        public let pieChart = UIImage.fromResources(by: "pie-chart")
        public let headphones = UIImage.fromResources(by: "headphones")
        public let rss = UIImage.fromResources(by: "rss")
        public let wifi = UIImage.fromResources(by: "wifi")
        public let cornerUpLeft = UIImage.fromResources(by: "corner-up-left")
        public let watch = UIImage.fromResources(by: "watch")
        public let info = UIImage.fromResources(by: "info")
        public let userX = UIImage.fromResources(by: "user-x")
        public let loader = UIImage.fromResources(by: "loader")
        public let refreshCcw = UIImage.fromResources(by: "refresh-ccw")
        public let folderPlus = UIImage.fromResources(by: "folder-plus")
        public let gitMerge = UIImage.fromResources(by: "git-merge")
        public let mic = UIImage.fromResources(by: "mic")
        public let copy = UIImage.fromResources(by: "copy")
        public let zoomIn = UIImage.fromResources(by: "zoom-in")
        public let arrowRightCircle = UIImage.fromResources(by: "arrow-right-circle")
        public let alignRight = UIImage.fromResources(by: "align-right")
        public let image = UIImage.fromResources(by: "image")
        public let maximize2 = UIImage.fromResources(by: "maximize-2")
        public let checkCircle = UIImage.fromResources(by: "check-circle")
        public let sunset = UIImage.fromResources(by: "sunset")
        public let save = UIImage.fromResources(by: "save")
        public let smile = UIImage.fromResources(by: "smile")
        public let navigation = UIImage.fromResources(by: "navigation")
        public let cloudLightning = UIImage.fromResources(by: "cloud-lightning")
        public let paperclip = UIImage.fromResources(by: "paperclip")
        public let fastForward = UIImage.fromResources(by: "fast-forward")
        public let xSquare = UIImage.fromResources(by: "x-square")
        public let award = UIImage.fromResources(by: "award")
        public let zoomOut = UIImage.fromResources(by: "zoom-out")
        public let box = UIImage.fromResources(by: "box")
        public let thumbsUp = UIImage.fromResources(by: "thumbs-up")
        public let percent = UIImage.fromResources(by: "percent")
        public let sidebar = UIImage.fromResources(by: "sidebar")
        public let square = UIImage.fromResources(by: "square")
        public let play = UIImage.fromResources(by: "play")
        public let gitCommit = UIImage.fromResources(by: "git-commit")
        public let table = UIImage.fromResources(by: "table")
        public let send = UIImage.fromResources(by: "send")
        public let phoneCall = UIImage.fromResources(by: "phone-call")
        public let speaker = UIImage.fromResources(by: "speaker")
        public let facebook = UIImage.fromResources(by: "facebook")
        public let codesandbox = UIImage.fromResources(by: "codesandbox")
        public let camera = UIImage.fromResources(by: "camera")
        public let link2 = UIImage.fromResources(by: "link-2")
        public let printer = UIImage.fromResources(by: "printer")
        public let folderMinus = UIImage.fromResources(by: "folder-minus")
        public let arrowUpRight = UIImage.fromResources(by: "arrow-up-right")
        public let truck = UIImage.fromResources(by: "truck")
        public let lifeBuoy = UIImage.fromResources(by: "life-buoy")
        public let penTool = UIImage.fromResources(by: "pen-tool")
        public let atSign = UIImage.fromResources(by: "at-sign")
        public let feather = UIImage.fromResources(by: "feather")
        public let trash = UIImage.fromResources(by: "trash")
        public let wifiOff = UIImage.fromResources(by: "wifi-off")
        public let cornerLeftDown = UIImage.fromResources(by: "corner-left-down")
        public let dollarSign = UIImage.fromResources(by: "dollar-sign")
        public let star = UIImage.fromResources(by: "star")
        public let cloudOff = UIImage.fromResources(by: "cloud-off")
        public let sun = UIImage.fromResources(by: "sun")
        public let messageSquare = UIImage.fromResources(by: "message-square")
        public let edit = UIImage.fromResources(by: "edit")
        public let anchor = UIImage.fromResources(by: "anchor")
        public let alertCircle = UIImage.fromResources(by: "alert-circle")
        public let chevronsUp = UIImage.fromResources(by: "chevrons-up")
        public let uploadCloud = UIImage.fromResources(by: "upload-cloud")
        public let twitch = UIImage.fromResources(by: "twitch")
        public let youtube = UIImage.fromResources(by: "youtube")
        public let unlock = UIImage.fromResources(by: "unlock")
        public let compass = UIImage.fromResources(by: "compass")
        public let plusCircle = UIImage.fromResources(by: "plus-circle")
        public let creditCard = UIImage.fromResources(by: "credit-card")
        public let cloudRain = UIImage.fromResources(by: "cloud-rain")
        public let trash2 = UIImage.fromResources(by: "trash-2")
        public let skipBack = UIImage.fromResources(by: "skip-back")
        public let filePlus = UIImage.fromResources(by: "file-plus")
        public let delete = UIImage.fromResources(by: "delete")
        public let command = UIImage.fromResources(by: "command")
        public let clock = UIImage.fromResources(by: "clock")
        public let octagon = UIImage.fromResources(by: "octagon")
        public let phone = UIImage.fromResources(by: "phone")
        public let eye = UIImage.fromResources(by: "eye")
        public let phoneOff = UIImage.fromResources(by: "phone-off")
        public let codepen = UIImage.fromResources(by: "codepen")
        public let dribbble = UIImage.fromResources(by: "dribbble")
        public let gift = UIImage.fromResources(by: "gift")
        public let externalLink = UIImage.fromResources(by: "external-link")
        public let zap = UIImage.fromResources(by: "zap")
        public let trello = UIImage.fromResources(by: "trello")
        public let moreVertical = UIImage.fromResources(by: "more-vertical")
        public let micOff = UIImage.fromResources(by: "mic-off")
        public let share = UIImage.fromResources(by: "share")
        public let arrowUp = UIImage.fromResources(by: "arrow-up")
        public let bellOff = UIImage.fromResources(by: "bell-off")
        public let linkedin = UIImage.fromResources(by: "linkedin")
        public let video = UIImage.fromResources(by: "video")
        public let divideCircle = UIImage.fromResources(by: "divide-circle")
        public let activity = UIImage.fromResources(by: "activity")
        public let twitter = UIImage.fromResources(by: "twitter")
        public let mapPin = UIImage.fromResources(by: "map-pin")
        public let filter = UIImage.fromResources(by: "filter")
        public let phoneIncoming = UIImage.fromResources(by: "phone-incoming")
        public let italic = UIImage.fromResources(by: "italic")
        public let chevronsLeft = UIImage.fromResources(by: "chevrons-left")
        public let calendar = UIImage.fromResources(by: "calendar")
        public let globe = UIImage.fromResources(by: "globe")
        public let arrowLeft = UIImage.fromResources(by: "arrow-left")
        public let alignCenter = UIImage.fromResources(by: "align-center")
        public let minusCircle = UIImage.fromResources(by: "minus-circle")
        public let arrowDownRight = UIImage.fromResources(by: "arrow-down-right")
        public let framer = UIImage.fromResources(by: "framer")
        public let volumeX = UIImage.fromResources(by: "volume-x")
        public let slack = UIImage.fromResources(by: "slack")
        public let cloud = UIImage.fromResources(by: "cloud")
        public let downloadCloud = UIImage.fromResources(by: "download-cloud")
        public let shuffle = UIImage.fromResources(by: "shuffle")
        public let rewind = UIImage.fromResources(by: "rewind")
        public let upload = UIImage.fromResources(by: "upload")
        public let trendingDown = UIImage.fromResources(by: "trending-down")
        public let pause = UIImage.fromResources(by: "pause")
        public let arrowDownCircle = UIImage.fromResources(by: "arrow-down-circle")
        public let bookmark = UIImage.fromResources(by: "bookmark")
        public let alertTriangle = UIImage.fromResources(by: "alert-triangle")
        public let userCheck = UIImage.fromResources(by: "user-check")
        public let tablet = UIImage.fromResources(by: "tablet")
        public let alertOctagon = UIImage.fromResources(by: "alert-octagon")
        public let menu = UIImage.fromResources(by: "menu")
        public let chrome = UIImage.fromResources(by: "chrome")
        public let shoppingCart = UIImage.fromResources(by: "shopping-cart")
        public let folder = UIImage.fromResources(by: "folder")
        public let users = UIImage.fromResources(by: "users")
        public let cornerDownLeft = UIImage.fromResources(by: "corner-down-left")
        public let monitor = UIImage.fromResources(by: "monitor")
        public let minus = UIImage.fromResources(by: "minus")
        public let helpCircle = UIImage.fromResources(by: "help-circle")
        public let navigation2 = UIImage.fromResources(by: "navigation-2")
        public let chevronLeft = UIImage.fromResources(by: "chevron-left")
        public let film = UIImage.fromResources(by: "film")
        public let moon = UIImage.fromResources(by: "moon")
        public let shieldOff = UIImage.fromResources(by: "shield-off")
        public let layout = UIImage.fromResources(by: "layout")
        public let mousePointer = UIImage.fromResources(by: "mouse-pointer")
        public let alignLeft = UIImage.fromResources(by: "align-left")
        public let heart = UIImage.fromResources(by: "heart")
        public let trendingUp = UIImage.fromResources(by: "trending-up")

    }
    
    public struct SFIcons {
        public let home = SFIcon(name: "house")
        public let document = SFIcon(name: "doc")
        public let dollar = SFIcon(name: "dollarsign")
        public let user = SFIcon(name: "person")
        
        public let enginePower = SFIcon(name: "bolt")
        public let distance = SFIcon(name: "road.lanes")
        public let engineVolume = SFIcon(name: "engine.combustion")
        public let maxSpeedometr = SFIcon(name: "gauge.with.dots.needle.100percent")
        public let stopwatch = SFIcon(name: "stopwatch")
        public let fuelpump = SFIcon(name: "fuelpump")
        
        
        
        
    }
    
    public struct Brands {
        public let rosneft = UIImage.fromResources(by: "rosneft")
        public let lukoil = UIImage.fromResources(by: "lukoil")
        public let gazpromneft = UIImage.fromResources(by: "gazpromneft")
    }
    
    public let icons: Icons = Icons()
    public let sfIcons: SFIcons = SFIcons()
    public let brands: Brands = Brands()
}

public extension UIImage {
    static let appImages = AppImages()
    
}

public extension UIImage {
    static func fromResources(by named: String) -> UIImage {
        guard let image = self.init(named: named, in: .module, with: nil) else {
            fatalError("Not found image by named \(named)")
        }
        return image
    }
}

public extension UIImage {
    static func fromSF(by named: String, size: CGFloat = 16, weight: UIImage.SymbolWeight = .regular) -> UIImage {
        let config = UIImage.SymbolConfiguration(pointSize: size, weight: weight)
        guard let icon = UIImage(
            systemName: named,
            withConfiguration: config
        ) else {
            fatalError("Not found SF image by named \(named)")
        }
        return icon
    }
}

public extension UIImage {
    static func getFromResources(by named: String) -> UIImage {
        guard let image = self.init(named: named, in: .module, with: nil) else {
            fatalError("Not found image by named \(named)")
        }
        return image
    }
}
